CREATE TABLE CUSTOMER(CUSTOMER_ID BIGINT GENERATED BY DEFAULT AS IDENTITY , 
Customer_Name VARCHAR(100) ,
Customer_Contact BIGINT , 
Address VARCHAR(100) , 
Gender VARCHAR(10));

INSERT INTO Customer(Customer_Name , Customer_Contact ,Address , Gender) VALUES ('JOHN' , 1231231232 , 'MISSOURI', 'MALE');
INSERT INTO Customer(Customer_Name , Customer_Contact ,Address , Gender) VALUES ('JANE' , 7897897897 , 'OHIO', 'FEMALE');